spring.application.name=event-planner-api

# application.properties
frontend.base-url=${FRONTEND_BASE_URL}

discord.client-id=${DISCORD_CLIENT_ID}
discord.client-secret=${DISCORD_CLIENT_SECRET}
discord.bot-token=${DISCORD_BOT_TOKEN}
discord.redirect-uri=${DISCORD_REDIRECT_URI}

discord.target-guild-ids[0]=${DISCORD_GUILD_ID_0:}

discord.target-role-ids[0]=${DISCORD_ROLE_ID_0:}

# session limit(15 days)
server.servlet.session.cookie.max-age=1296000s
server.servlet.session.timeout=1296000s

server.forward-headers-strategy=framework

server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=none