spring.application.name=event-planner-api

# application-dev.properties
discord.client-id=${DISCORD_CLIENT_ID}
discord.client-secret=${DISCORD_CLIENT_SECRET}
discord.bot-token=${DISCORD_BOT_TOKEN}
discord.redirect-uri=${DISCORD_REDIRECT_URI}

# soraneko
discord.target-guild-ids[0]=${DISCORD_GUILD_ID_0:}

# soraneko->9syunenn
discord.target-role-ids[0]=${DISCORD_ROLE_ID_0:}

# session limit(15 days)
server.servlet.session.cookie.max-age=1296000s
server.servlet.session.timeout=1296000s

server.forward-headers-strategy=framework