name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build frontend Docker image
      run: docker build -t event-planner-frontend:test ./frontend

  backend-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build backend Docker image
      run: docker build -t event-planner-api:test ./event-planner-api
